# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pasali.me" # the base hostname & protocol for your site

# mytheme-SPECIFIC CONFIGURATION
mytheme:
  # Meta
  title: Mehmet Başal
  avatar: avatar.png
  description: "A website with blog posts, and pages." # used by search engines

  # Header and footer text
  header_text:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type.html">Type mytheme</a>

  # Icons
  rss: false
  email_address: mhmtbsl@gmail.com
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "pasali"
  google_plus:
  instagram:
  linkedin: https://www.linkedin.com/in/pasali
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # full URL
  steam:
  tumblr:
  twitter: "p4s4li"
  wordpress:
  youtube:

  # Scripts
  google_analytics: # tracking id, e.g. "UA-000000-01"
  disqus_shortname: pasali

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Sonraki"
  str_prev: "Önceki"
  str_continue_reading: "Devamını oku"

  # Colors, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed


gems: [jekyll-paginate]
